namespace PreApproveMeApi.Integrations.Loan.Types.V1
{
    public enum LoanIntegrationIncomeType
    {
        MilitaryBasePay = 1,
        MilitaryRationsAllowance = 2,
        MilitaryFlightPay = 3,
        MilitaryHazardPay = 4,
        MilitaryClothesAllowance = 5,
        MilitaryQuartersAllowance = 6,
        MilitaryPropPay = 7,
        MilitaryOverseasPay = 8,
        MilitaryCombatPay = 9,
        MilitaryVariableHousingAllowance = 10,
        AlimonyChildSupport = 11,
        NotesReceivableOrInstallment = 12,
        PensionOrRetirement = 13,
        SocialSecurityOrDisability = 14,
        RealEstateOrMortgageDifferential = 15,
        Trust = 16,
        AccessoryUnit = 17,
        Unemployment = 18,
        AutomobileOrExpenseAccount = 19,
        FosterCare = 20,
        VABenefit = 21,
        NonBorrowerHouseholdIncome = 22,
        Other = 23,
        BaseEmployment = 24,
        Overtime = 25,
        Bonuses = 26,
        Commissions = 27,
        DividendsInterest = 28,
        SubjectPropertyNet = 29,
        Section8Voucher = 30,
        NetRental = 31,
        Boarder = 32,
        MortgageCreditCertificate = 33,
        CapitalGains = 34,
        EmploymentAssets = 35,
        Foreign = 36,
        RoyaltyPayment = 37,
        Seasonal = 38,
        TemporaryLeave = 39,
        Tips = 40
    }
}