namespace PreApproveMeApi.Integrations.Loan.Types.V2
{
    public enum LoanIntegrationIncomeType
    {
        AccessoryUnitIincome = 1,
        Alimony = 2,
        AutomobileAllowance = 3,
        Base = 4,
        BoarderIncome = 5,
        Bonus = 6,
        CapitalGains = 7,
        ChildSupport = 8,
        Commissions = 9,
        ContractBasis = 10,
        DefinedContributionPlan = 11,
        Disability = 12,
        DividendsInterest = 13,
        EmploymentRelatedAccount = 14,
        FosterCare = 15,
        HousingAllowance = 16,
        HousingChoiceVoucherProgram = 17,
        MilitaryBasePay = 18,
        MilitaryClothesAllowance = 19,
        MilitaryCombatPay = 20,
        MilitaryFlightPay = 21,
        MilitaryHazardPay = 22,
        MilitaryOverseasPay = 23,
        MilitaryPropPay = 24,
        MilitaryQuartersAllowance = 25,
        MilitaryRationsAllowance = 26,
        MilitaryVariableHousingAllowance = 27,
        MortgageCreditCertificate = 28,
        MortgageDifferential = 29,
        NonBorrowerHouseholdIncome = 30,
        NotesReceivableInstallment = 31,
        Other = 32,
        Overtime = 33,
        Pension = 34,
        PublicAssistance = 35,
        Royalties = 36,
        SeparateMaintenance = 37,
        SocialSecurity = 38,
        TemporaryLeave = 39,
        TipIncome = 40,
        Trust = 41,
        Unemployment = 42,
        VABenefitsNonEducational = 43
    }
}